//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestListen360API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestListen360API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;custom-attribute-definition&gt;
        ///  &lt;id type=&quot;integer&quot;&gt;205&lt;/id&gt;
        ///  &lt;created-at type=&quot;datetime&quot;&gt;2009-04-13T03:47:34-04:00&lt;/created-at&gt;
        ///  &lt;mandatory type=&quot;boolean&quot;&gt;false&lt;/mandatory&gt;
        ///  &lt;name&gt;Source&lt;/name&gt;
        ///  &lt;ordinal type=&quot;integer&quot;&gt;1&lt;/ordinal&gt;
        ///  &lt;restrict-to-predefined-choices type=&quot;boolean&quot;&gt;false&lt;/restrict-to-predefined-choices&gt;
        ///  &lt;updated-at type=&quot;datetime&quot;&gt;2009-04-13T03:47:34-04:00&lt;/updated-at&gt;
        ///  &lt;attach-to&gt;Job&lt;/attach-to&gt;
        ///  &lt;organization-id type=&quot;integer&quot;&gt;1000&lt;/organization-id&gt;
        ///&lt;/custom-attribute-definition&gt;.
        /// </summary>
        internal static string FakeCustomAttributeDefinition1 {
            get {
                return ResourceManager.GetString("FakeCustomAttributeDefinition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;customer&gt;
        ///  &lt;id type=&quot;integer&quot;&gt;3&lt;/id&gt;
        ///  &lt;first-name&gt;Jane&lt;/first-name&gt;
        ///  &lt;last-name&gt;Doe&lt;/last-name&gt;
        ///  &lt;full-name&gt;Jane Doe&lt;/full-name&gt;
        ///  &lt;name nil=&quot;true&quot;&gt;&lt;/name&gt;
        ///  &lt;reference&gt;4264465&lt;/reference&gt;
        ///  &lt;status&gt;Active&lt;/status&gt;
        ///  &lt;title&gt;Mrs&lt;/title&gt;
        ///  &lt;net-promoter-label&gt;Promoter&lt;/net-promoter-label&gt;
        ///  &lt;company-name&gt;Acme Corp&lt;/company-name&gt;
        ///  &lt;mobile-phone-number&gt;111-111-1111&lt;/mobile-phone-number&gt;
        ///  &lt;organization-id type=&quot;integer&quot;&gt;2&lt;/organization-id&gt;
        ///  &lt;work-city&gt;Hollywood&lt;/work-city&gt;
        ///  &lt;work-country&gt;US&lt;/work-countr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FakeCustomer1 {
            get {
                return ResourceManager.GetString("FakeCustomer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;division&gt;
        ///  &lt;id type=&quot;integer&quot;&gt;2&lt;/id&gt;
        ///  &lt;type&gt;Division&lt;/type&gt;
        ///  &lt;parent-id type=&quot;integer&quot;&gt;1&lt;/parent-id&gt;
        ///  &lt;name&gt;Northern Region&lt;/name&gt;
        ///  &lt;external-name&gt;Northern Region&lt;/external-name&gt;
        ///&lt;/division&gt;.
        /// </summary>
        internal static string FakeDivision1 {
            get {
                return ResourceManager.GetString("FakeDivision1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;franchise&gt;
        ///  &lt;id type=&quot;integer&quot;&gt;2&lt;/id&gt;
        ///  &lt;type&gt;Franchise&lt;/type&gt;
        ///  &lt;parent-id type=&quot;integer&quot;&gt;1&lt;/parent-id&gt;
        ///  &lt;root-id type=&quot;integer&quot;&gt;1&lt;/root-id&gt;
        ///  &lt;name&gt;Proserv&lt;/name&gt;
        ///  &lt;external-name&gt;Proserv of Atlanta&lt;/external-name&gt;
        ///  &lt;email&gt;joe.franchisee@example.com&lt;/email&gt;
        ///  &lt;reference&gt;franchise-1&lt;/reference&gt;
        ///  &lt;status&gt;Active&lt;/status&gt;
        ///  &lt;street-address&gt;1 North Point Pkwy&lt;/street-address&gt;
        ///  &lt;city&gt;Alpharetta&lt;/city&gt;
        ///  &lt;region&gt;GA&lt;/region&gt;
        ///  &lt;postal-code&gt;30022&lt;/postal-code&gt;
        ///  &lt;country&gt;US&lt;/country&gt;
        ///  &lt;time-zone&gt;Eastern Tim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FakeFranchise1 {
            get {
                return ResourceManager.GetString("FakeFranchise1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;franchise&gt;
        ///  &lt;id type=&quot;integer&quot;&gt;3&lt;/id&gt;
        ///  &lt;type&gt;Franchise&lt;/type&gt;
        ///  &lt;parent-id type=&quot;integer&quot;&gt;1&lt;/parent-id&gt;
        ///  &lt;root-id type=&quot;integer&quot;&gt;1&lt;/root-id&gt;
        ///  &lt;name&gt;Proserv&lt;/name&gt;
        ///  &lt;external-name&gt;Proserv of Macon&lt;/external-name&gt;
        ///  &lt;email&gt;joe.franchisee@example.com&lt;/email&gt;
        ///  &lt;reference&gt;franchise-2&lt;/reference&gt;
        ///  &lt;status&gt;Active&lt;/status&gt;
        ///  &lt;street-address&gt;1 North Point Pkwy&lt;/street-address&gt;
        ///  &lt;city&gt;Macon&lt;/city&gt;
        ///  &lt;region&gt;GA&lt;/region&gt;
        ///  &lt;postal-code&gt;31201&lt;/postal-code&gt;
        ///  &lt;country&gt;US&lt;/country&gt;
        ///  &lt;time-zone&gt;Eastern Time (US &amp; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FakeFranchise2 {
            get {
                return ResourceManager.GetString("FakeFranchise2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;franchisor&gt;
        ///  &lt;id type=&quot;integer&quot;&gt;1&lt;/id&gt;
        ///  &lt;type&gt;Franchisor&lt;/type&gt;
        ///  &lt;root-id type=&quot;integer&quot;&gt;1&lt;/root-id&gt;
        ///  &lt;parent-id type=&quot;integer&quot;&gt;&lt;/parent-id&gt;
        ///  &lt;name&gt;Proserv Inc&lt;/name&gt;
        ///  &lt;external-name&gt;Proserv&lt;/external-name&gt;
        ///  &lt;email&gt;joe.franchisor@example.com&lt;/email&gt;
        ///  &lt;status&gt;Active&lt;/status&gt;
        ///  &lt;street-address&gt;1 Mansell Road&lt;/street-address&gt;
        ///  &lt;city&gt;Alpharetta&lt;/city&gt;
        ///  &lt;region&gt;GA&lt;/region&gt;
        ///  &lt;postal-code&gt;30022&lt;/postal-code&gt;
        ///  &lt;country&gt;US&lt;/country&gt;
        ///  &lt;time-zone&gt;Eastern Time (US &amp;amp; Canada)&lt;/time-zone&gt;
        ///  &lt;phone-number [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FakeFranchisor1 {
            get {
                return ResourceManager.GetString("FakeFranchisor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;job&gt;
        ///  &lt;id type=&quot;integer&quot;&gt;234&lt;/id&gt;
        ///  &lt;organization-id type=&quot;integer&quot;&gt;1&lt;/organization-id&gt;
        ///  &lt;customer-id type=&quot;integer&quot;&gt;5&lt;/customer-id&gt;
        ///  &lt;reference&gt;job-ref-1&lt;/reference&gt;
        ///  &lt;status&gt;Completed&lt;/status&gt;
        ///  &lt;value type=&quot;decimal&quot;&gt;575.37&lt;/value&gt;
        ///  &lt;currency&gt;USD&lt;/currency&gt;
        ///  &lt;performers type=&quot;array&quot;&gt;
        ///    &lt;performer type=&quot;Technician&quot;&gt;
        ///      &lt;id type=&quot;integer&quot;&gt;15&lt;/id&gt;
        ///      &lt;organization-id type=&quot;integer&quot;&gt;1&lt;/organization-id&gt;
        ///      &lt;name&gt;Albert Smith&lt;/name&gt;
        ///      &lt;reference&gt;tech-ref-2&lt;/reference&gt;
        ///      &lt;email nil=&quot;tru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FakeJob1 {
            get {
                return ResourceManager.GetString("FakeJob1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;membership&gt;
        ///  &lt;accepted-at type=&quot;datetime&quot;&gt;2008-12-31T07:56:47-04:00&lt;/accepted-at&gt;
        ///  &lt;country&gt;US&lt;/country&gt;
        ///  &lt;created-at type=&quot;datetime&quot;&gt;2008-12-31T07:56:47-04:00&lt;/created-at&gt;
        ///  &lt;email&gt;joe.franchisee@example.com&lt;/email&gt;
        ///  &lt;first-name&gt;Joe&lt;/first-name&gt;
        ///  &lt;id type=&quot;integer&quot;&gt;20&lt;/id&gt;
        ///  &lt;invited-by-id type=&quot;integer&quot; nil=&quot;true&quot;&gt;&lt;/invited-by-id&gt;
        ///  &lt;last-name&gt;Franchisee&lt;/last-name&gt;
        ///  &lt;mobile-phone-number&gt;555-444-3333&lt;/mobile-phone-number&gt;
        ///  &lt;organization-id type=&quot;integer&quot;&gt;2&lt;/organization-id&gt;
        ///  &lt;revoked-at type=&quot;dat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FakeMembership1 {
            get {
                return ResourceManager.GetString("FakeMembership1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;technician&gt;
        ///  &lt;country&gt;US&lt;/country&gt;
        ///  &lt;created-at type=&quot;datetime&quot;&gt;2009-12-08T11:29:15-05:00&lt;/created-at&gt;
        ///  &lt;email&gt;albert.smith@example.com&lt;/email&gt;
        ///  &lt;id type=&quot;integer&quot;&gt;15&lt;/id&gt;
        ///  &lt;mobile-phone-number&gt;333-444-5555&lt;/mobile-phone-number&gt;
        ///  &lt;name&gt;Albert Smith&lt;/name&gt;
        ///  &lt;organization-id type=&quot;integer&quot;&gt;1&lt;/organization-id&gt;
        ///  &lt;reference&gt;TECH100&lt;/reference&gt;
        ///  &lt;status&gt;Active&lt;/status&gt;
        ///&lt;/technician&gt;.
        /// </summary>
        internal static string FakeTechnician1 {
            get {
                return ResourceManager.GetString("FakeTechnician1", resourceCulture);
            }
        }
    }
}
